# data
discovery-enabled=false
data-path="<%= rootDir %>/data"
logging="INFO"

# private_key
node-private-key-file="<%= rootDir %>/key"

genesis-file="<%= rootDir %>/genesis.json"
min-gas-price=1000
sync-mode="FULL"
host-whitelist=["*"]

# rpc
rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8545
rpc-http-api=["DEBUG","NET","WEB3","ETH","ADMIN","PERM","MINER","EEA","PRIV","TXPOOL","CLIQUE"]
rpc-http-cors-origins=["all"]

# ws
rpc-ws-enabled=true
rpc-ws-api=["NET","ETH","WEB3"]
rpc-ws-host="0.0.0.0"
rpc-ws-port=8546

# p2p
p2p-host="<%= p2pHost %>"
p2p-port=30303

# eip1559 testnet
Xeip1559-enabled=true

<% if (ethStatsEnabled) { %>Xethstats="<%- ethStatsURL %>"
<%}-%>
